streamx.blueprints.data-collector.web-resources.filters=:collected:.*
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.data-key-match-pattern=product:.*
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.collector=aggregate-by-property-value
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.outputkeyprefix=:collected:products:cheapest-by-category:
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.groupby=categories/slug
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sortby=price/value
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sortmode=asc
streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.max=8

streamx.blueprints.data-collector.configurations.featured-by-category.data-key-match-pattern=product:.*
streamx.blueprints.data-collector.configurations.featured-by-category.collector=aggregate-by-property-value
streamx.blueprints.data-collector.configurations.featured-by-category.properties.outputkeyprefix=:collected:products:featured-by-category:
streamx.blueprints.data-collector.configurations.featured-by-category.properties.groupby=categories/slug
streamx.blueprints.data-collector.configurations.featured-by-category.properties.max=8
streamx.blueprints.data-collector.configurations.featured-by-category.properties.filterby=$.categories[?(@.name == 'Featured')]
