streamx.blueprints.json-aggregator.configurations.pim.master-namespace=pim
streamx.blueprints.json-aggregator.configurations.pim.optional-namespaces=price,reviews
streamx.blueprints.json-aggregator.configurations.pim.output-namespace=product

streamx.blueprints.json-aggregator.configurations.reviews.master-namespace=review
streamx.blueprints.json-aggregator.configurations.reviews.output-namespace=reviews

streamx.blueprints.json-aggregator.configurations.categories.master-namespace=cat
streamx.blueprints.json-aggregator.configurations.categories.output-namespace=category
#below config is for PRFT magento store
streamx.blueprints.json-aggregator.configurations.puresight-products.master-namespace=lumax_product
streamx.blueprints.json-aggregator.configurations.puresight-products.optional-namespaces=price,reviews
streamx.blueprints.json-aggregator.configurations.puresight-products.output-namespace=product

streamx.blueprints.json-aggregator.configurations.puresight-categories.master-namespace=lumax_category
streamx.blueprints.json-aggregator.configurations.puresight-categories.output-namespace=category
