quarkus.container-image.group=lumax
quarkus.container-image.name=lumax-json-processing-service
quarkus.container-image.tag=v1
quarkus.rest-client.spring-boot-ai.url=https://lumaxragdemo-cef8aeeqdkawbbc4.eastus-01.azurewebsites.net