spring.application.name=ai
spring.ai.vertex.ai.embedding.project-id=<INSERT PROJECT ID>
spring.ai.vertex.ai.embedding.location=us-central1
spring.autoconfigure.exclude=org.springframework.ai.model.vertexai.autoconfigure.embedding.VertexAiEmbeddingAutoConfiguration
spring.ai.vertex.ai.gemini.project-id=<INSERT PROJECT ID>
spring.ai.vertex.ai.embedding.text.options.model=gemini-embedding-001
# The region you want to use (e.g., us-central1, europe-west1)
spring.ai.vertex.ai.gemini.location=us-central1

# Optional: Specific model selection (default is usually gemini-2.0-flash)
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash

spring.ai.vectorstore.cosmosdb.endpoint=https://lumax.documents.azure.com:443/
spring.ai.vectorstore.cosmosdb.key=<INSERT_KEY>
spring.ai.vectorstore.cosmosdb.database-name=lumaxdb
spring.ai.vectorstore.cosmosdb.container-name=productstest

# Metadata & Partitioning
spring.ai.vectorstore.cosmosdb.partition-key-path=/id
spring.ai.vectorstore.cosmosdb.vector-dimensions=3072

spring.ai.vectorstore.cosmosdb.initialize-schema=true