<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.prft.lumax</groupId>
        <artifactId>lumax-project</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>lumax-services</artifactId>
    <name>LumaX Services</name>
    <packaging>pom</packaging>

    <modules>
        <module>web-delivery-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.spullara.mustache.java</groupId>
                <artifactId>compiler</artifactId>
                <version>0.9.4</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>