apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: aem-upstream
spec:
  scheme: https
  passHost: node
  externalNodes:
    - type: Domain
      name: publish-p7752-e729659.adobeaemcloud.com
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: aem-graphql-route
spec:
  http:
    - name: aem-graphql-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /aemgraphql/*
      priority: 15
      plugins:
      - name: cors
        enable: true
        config:
          allow_origins: "*"  # Change this to specific origins if needed
          allow_methods: "*"   # Allow all HTTP methods
          allow_headers: "*"   # Allow all headers
          expose_headers: "*"  # Expose all headers
          max_age: 3600
      upstreams:
        - name: aem-upstream
