apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: aem-upstream
spec:
  scheme: https
  passHost: node
  externalNodes:
    - type: Domain
      name: publish-p7752-e729659.adobeaemcloud.com
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: aem-graphql-route
spec:
  http:
    - name: aem-graphql-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /aemgraphql/*
      priority: 15
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/aemgraphql/(.*)"
              - "/graphql/$1"
        - name: response-rewrite
          enable: true
          config:
            headers:
              Cache-Control: "no-store, no-cache, must-revalidate"
              Pragma: "no-cache"
              Expires: "0"
      upstreams:
        - name: aem-upstream
