apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: aem-upstream
spec:
  scheme: https
  passHost: node
  externalNodes:
    - type: Domain
      name: https://publish-p7752-e729659.adobeaemcloud.com

---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: aem-graphql-route
spec:
  http:
    - name: aem-graphql-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /aemgraphql
      priority: 15
      uri: /graphql/execute.json
      upstreams:
        - name: aem-upstream
