apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ai-service-route
spec:
  http:
    - name: ai-service-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /api/products
          - /api/products/*
      priority: 30
      backends:
        - serviceName: ai-service
          servicePort: 80
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
            max_age: 3600