apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: lumaxai-upstream
spec:
  scheme: https
  passHost: node
  externalNodes:
    - type: Domain
      name: wonderful-flower-0ae435e0f.3.azurestaticapps.net
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: lumaxai-default-route
spec:
  http:
    - name: lumaxai-default-route
      match:
        hosts:
          - lumax.streamx.com
        paths:
          - /ai
          - /_next/*
          - /logo.svg
          - /voiceIcon.svg
          - /favicon.ico
          - /germ.svg
          - /api/*
          - /voiceCancel.svg
          - /hero-home.jpg
          - /voice*.mp3
          - /_next/image*
          - /audio-*.js
          - /video*.mp4
      priority: 10
      upstreams:
        - name: lumaxai-upstream
      plugins:
        - proxy-rewrite:
          status_code: 200
          body: "This is a fallback response for non-existing pages"
          config:
            regex_uri: ["^/(.*)","$1"]
            host: "wonderful-flower-0ae435e0f.3.azurestaticapps.net"
        - name: response-rewrite
          enable: true
          config:
            headers:
              Cache-Control: "no-store, no-cache, must-revalidate"
              Pragma: "no-cache"
              Expires: "0"
            vars:
              - [ "sent_http_content_type", "~~", "text/html" ]
