
###############################################
# StreamX Mesh Debug Mode (NO mesh.yaml needed)
###############################################

pulsar.client.serviceUrl=pulsar://localhost:6650

# === Incoming channel ===
mp.messaging.incoming.incoming-strings.topic=persistent://streamx/local/inboxes/incoming-strings

# === Outgoing channel ===
mp.messaging.outgoing.capitalized-strings.topic=persistent://streamx/local/outboxes/capitalized-strings
